import type { WorkspaceData } from "./types";
export const demoWorkspace: WorkspaceData = {
  organizationId: "demo",
  organizationName: "North Collective",
  mode: "demo",
  canWriteTasks: true,
  restaurants: [
    { id: "north", name: "Север · бистро", address: "ул. Лесная, 12" },
    { id: "ember", name: "Искра · бар", address: "ул. Малая, 8" },
  ],
  tasks: [
    {
      id: "t1",
      restaurantId: "north",
      title: "Проверить поставку от фермеров",
      status: "todo",
      priority: "high",
      assignee: "Алексей М.",
      due: "До 12:00",
    },
    {
      id: "t2",
      restaurantId: "north",
      title: "Подготовить зал к вечерней посадке",
      status: "in_progress",
      priority: "normal",
      assignee: "Мария К.",
      due: "До 17:00",
    },
    {
      id: "t3",
      restaurantId: "north",
      title: "Провести брифинг по осеннему меню",
      status: "todo",
      priority: "normal",
      assignee: "Анна С.",
      due: "До 16:30",
    },
    {
      id: "t4",
      restaurantId: "north",
      title: "Проверить стоп-лист кухни",
      status: "done",
      priority: "normal",
      assignee: "Дмитрий В.",
      due: "До 11:00",
    },
    {
      id: "t5",
      restaurantId: "north",
      title: "Обновить выкладку десертов",
      status: "done",
      priority: "normal",
      assignee: "Мария К.",
      due: "До 11:30",
    },
    {
      id: "t6",
      restaurantId: "ember",
      title: "Подготовить заготовки для коктейлей",
      status: "todo",
      priority: "high",
      assignee: "Илья Р.",
      due: "До 18:00",
    },
    {
      id: "t7",
      restaurantId: "ember",
      title: "Проверить барный инвентарь",
      status: "done",
      priority: "normal",
      assignee: "Илья Р.",
      due: "До 16:00",
    },
  ],
  checklists: [
    {
      id: "c1",
      restaurantId: "north",
      title: "Открытие зала",
      kind: "opening",
      items: [
        { id: "c11", title: "Проверить чистоту столов и стульев", done: true },
        { id: "c12", title: "Подготовить приборы и салфетки", done: true },
        { id: "c13", title: "Проверить освещение и музыку", done: true },
        { id: "c14", title: "Проверить бронирования", done: false },
      ],
    },
    {
      id: "c2",
      restaurantId: "north",
      title: "Готовность кухни",
      kind: "opening",
      items: [
        { id: "c21", title: "Проверить температуры хранения", done: true },
        { id: "c22", title: "Проверить маркировку заготовок", done: true },
        { id: "c23", title: "Сверить стоп-лист", done: true },
      ],
    },
    {
      id: "c3",
      restaurantId: "north",
      title: "Закрытие смены",
      kind: "closing",
      items: [
        { id: "c31", title: "Убрать рабочие поверхности", done: false },
        { id: "c32", title: "Проверить оборудование", done: false },
        { id: "c33", title: "Передать смену управляющему", done: false },
      ],
    },
    {
      id: "c4",
      restaurantId: "ember",
      title: "Открытие бара",
      kind: "opening",
      items: [
        { id: "c41", title: "Проверить лёд и заготовки", done: true },
        { id: "c42", title: "Подготовить станцию", done: false },
      ],
    },
  ],
  employees: [
    {
      id: "e1",
      restaurantId: "north",
      name: "Анна Смирнова",
      position: "Управляющий",
      initials: "АС",
      active: true,
    },
    {
      id: "e2",
      restaurantId: "north",
      name: "Алексей Морозов",
      position: "Шеф-повар",
      initials: "АМ",
      active: true,
    },
    {
      id: "e3",
      restaurantId: "north",
      name: "Мария Кузнецова",
      position: "Официант",
      initials: "МК",
      active: true,
    },
    {
      id: "e4",
      restaurantId: "north",
      name: "Дмитрий Волков",
      position: "Су-шеф",
      initials: "ДВ",
      active: true,
    },
    {
      id: "e5",
      restaurantId: "ember",
      name: "Илья Романов",
      position: "Бар-менеджер",
      initials: "ИР",
      active: true,
    },
  ],
  menu: [
    {
      id: "m1",
      name: "Тыквенный суп",
      category: "Основное меню",
      price: 490,
      currency: "RUB",
      available: true,
      description: "Запечённая тыква, сливки, тыквенные семечки",
      allergens: ["Молоко"],
    },
    {
      id: "m2",
      name: "Бриошь с лососем",
      category: "Завтраки",
      price: 720,
      currency: "RUB",
      available: true,
      description: "Бриошь, слабосолёный лосось, яйцо пашот",
      allergens: ["Рыба", "Глютен", "Яйцо"],
    },
    {
      id: "m3",
      name: "Груша и рикотта",
      category: "Десерты",
      price: 420,
      currency: "RUB",
      available: false,
      description: "Карамелизированная груша, рикотта, фундук",
      allergens: ["Молоко", "Орехи"],
    },
    {
      id: "m4",
      name: "Фильтр-кофе",
      category: "Напитки",
      price: 250,
      currency: "RUB",
      available: true,
      description: "Зерно недели · Эфиопия",
      allergens: [],
    },
  ],
  training: [
    {
      id: "l1",
      title: "Гостеприимство начинается с нас",
      status: "published",
      content:
        "Встретьте гостя, поздоровайтесь и уточните, есть ли бронирование. Предложите удобное место и меню. Если стол пока не готов, честно сообщите время ожидания и предложите альтернативу.",
    },
    {
      id: "l2",
      title: "Осеннее меню: вкус и состав",
      status: "published",
      content:
        "Перед сменой изучите состав блюд и стоп-лист. Вопросы об аллергенах всегда сверяйте с актуальной технологической картой и кухней. Не давайте гостю обещаний, если состав не подтверждён.",
    },
    {
      id: "l3",
      title: "Идеальное закрытие смены",
      status: "draft",
      content:
        "Пройдите чек-лист закрытия, проверьте оборудование и передайте незавершённые задачи следующей смене. Сообщите управляющему о неисправностях.",
    },
  ],
};
